name: auto-pull-request
on:
    push:
        branches:
            -   develop
jobs:
    create-pull-request:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
                with:
                    ref: main
            -   name: reset promotion branch
                run: |
                    git fetch origin develop:develop
                    git reset --hard develop
            -   name: Create Pull Request
                uses: peter-evans/create-pull-request@v5.0.2
                with:
                    token: ${{ secrets.REPO_TOKEN }}
                    author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
                    title: 'Branch Promotion'