name: get-tag-sha
on:
    workflow_dispatch:
        inputs:
            tag:
                description: 'The tag to get the SHA of'
                required: true
jobs:
    get-tag-sha:
        runs-on: ubuntu-latest
        steps:
            - name: Get Tag SHA - Powershell
              run: |
                  $REPO_NAME = "RobertPuffeEldermark/PowerShell"


                  SHA=$(curl -L -X GET \
                  -H "Accept: application/vnd.github+json" \
                  -H "Authorization: Bearer ${{ secrets.REPO_TOKEN }}" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  https://api.github.com/repos/${REPO_NAME}/git/ref/tags/${{ github.event.inputs.tag }})

                  echo "SHA: $SHA"