name: get-tag-sha
on:
    workflow_dispatch:
        inputs:
            tag:
                description: 'The tag to get the SHA of'
                required: true
env:
    POWERSHELL_REPO: 'RobertPuffeEldermark/PowerShell'
jobs:
    get-tag-sha:
        runs-on: ubuntu-latest
        steps:
            - name: Get Tag SHA - Powershell
              id: powershell-get-tag-sha
              run: |
                  POWERSHELL_SHA=$(curl -L -X GET \
                  -H "Accept: application/vnd.github+json" \
                  -H "Authorization: Bearer ${{ secrets.REPO_TOKEN }}" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  https://api.github.com/repos/${{ env.POWERSHELL_REPO }}/git/ref/tags/${{ github.event.inputs.tag }} \
                  | jq -r '.object.sha')

                  echo "SHA=$POWERSHELL_SHA" >> $GITHUB_OUTPUT

            - name: print output
              run: |
                  echo ${{ steps.powershell-get-tag-sha.outputs.SHA }}