name: get-tag-sha
on:
    workflow_dispatch:
        inputs:
            tag:
                description: 'The tag to get the SHA of'
                required: true
env:
    POWERSHELL_REPO: 'RobertPuffeEldermark/PowerShell'
    ELDERMARK_REPO: 'LivTechCos/eldermark'

jobs:
    powershell-get-tag-sha:
        runs-on: ubuntu-latest
        concurrency:
            group: ${{ github.workflow }}-get-tag-sha
        steps:
            - name: Get Tag SHA - Powershell
              id: powershell-get-tag-sha
              run: |
                  SHA=$(curl -L -X GET \
                  -H "Accept: application/vnd.github+json" \
                  -H "Authorization: Bearer ${{ secrets.REPO_TOKEN }}" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  https://api.github.com/repos/${{ env.POWERSHELL_REPO }}/git/ref/tags/${{ github.event.inputs.tag }} \
                  | jq -r '.object.sha')

                  echo "SHA=$SHA" >> $GITHUB_OUTPUT

            - name: print output
              run: |
                  echo ${{ steps.powershell-get-tag-sha.outputs.SHA }}
            - name: Get Tag SHA - eldermark
              id: eldermark-get-tag-sha
              run: |
                  SHA=$(curl -L -X GET \
                  -H "Accept: application/vnd.github+json" \
                  -H "Authorization: Bearer ${{ secrets.REPO_TOKEN }}" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  https://api.github.com/repos/${{ env.ELDERMARK_REPO }}/git/ref/tags/${{ github.event.inputs.tag }} \
                  | jq -r '.object.sha')

                  echo "SHA=$SHA" >> $GITHUB_OUTPUT

            - name: print output
              run: |
                  echo "eldermark" ${{ steps.eldermark-get-tag-sha.outputs.SHA }}
                  echo "powershell" ${{ steps.powershell-get-tag-sha.outputs.SHA }}