name: Test-AWS-CLI

on: 
  workflow_dispatch:
    inputs:
      command:
        description: 'The AWS CLI command to run'
        required: true
        default: 'aws s3 ls'

jobs:
  test-aws-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Test AWS CLI
        run: |
          echo "Running AWS CLI command: ${{ github.event.inputs.command }}"
          ${{ github.event.inputs.command }}