name: Trigger Create Release

on: 
  workflow_dispatch:
    inputs:
        target_workflow:
            description: 'The filename of the workflow to trigger'
            required: true
            default: 'createrelase_local.yml'
        ReleaseName:
            description: 'Name of release. ex. Sprint 6 Close'
            type: string
            required: true
        ReleaseInfoFile:
            description: 'Release Info File'
            type: string
            required: true
            default: 'releases/ReleaseInfo.md'
jobs:
    # ToDo: use github api to get tags from each repository and calculate new tag. 
    # ToDo: Add concurrency
    trigger-create-release:
        runs-on: ubuntu-latest
        steps:
        - name: Get the date
          id: get-date
          run: echo "date=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT
        - name: fetch tags on repos
          id: fetch-tags
          run: |
            echo "fetching tags"


            REPOSITORIES=("RobertPuffeEldermark/PowerShell" "RobertPuffeEldermark/test-auto-pr-2")
            GREATEST_TAG=0000.00.00.0000
            for REPO in "${REPOSITORIES[@]}" ; do
                TAG=$(curl -L -X GET \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.REPO_TOKEN }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/$REPO/git/refs/tags \
                | jq -r '.[] | select(.ref | contains("${{ steps.get-date.outputs.date }}")) | .ref' | cut -d '/' -f 3)
                echo "Tag for $REPO is $TAG"
                if [[ -z "$TAG" ]]; then
                    echo "No tag found for $REPO Setting to 0000.00.00.0000"
                    TAG=0000.00.00.0000
                    continue
                fi
                echo "TAG_$REPO=$TAG" >> $GITHUB_OUTPUT
                if [[ $TAG > $GREATEST_TAG ]]; then
                    GREATEST_TAG=$TAG
                    echo "GREATEST_TAG=$GREATEST_TAG" >> $GITHUB_OUTPUT
                    echo "greater tag found $TAG"
                fi
            done
        
        - name: Calculate new tag
          id: new-tag
          run: |
            OLD_TAG=${{ steps.fetch-tags.outputs.GREATEST_TAG}}
            if [[ -z "$OLD_TAG" ]]; then
            echo "tag=${{ steps.get-date.outputs.date }}.0001" >> $GITHUB_OUTPUT
            else
            NUMBER=$(echo $OLD_TAG | awk -F. '{print $NF}')
            NEW_NUMBER=$(printf "%04d" $((10#$NUMBER + 1)))
            echo "tag=${{ steps.get-date.outputs.date }}.$NEW_NUMBER" >> $GITHUB_OUTPUT
            fi

        # Trigger Repository 1
        - name: Trigger Target Workflow - Powershell
          run: |       
            REPO=("RobertPuffeEldermark/PowerShell" "RobertPuffeEldermark/test-auto-pr-2")
            for REPO in "${REPO[@]}" ; do
                echo "Triggering workflow for $REPO"   
                curl -L -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.REPO_TOKEN_RP }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/RobertPuffeEldermark/PowerShell/actions/workflows/${{ github.event.inputs.target_workflow }}/dispatches \
                -d '{
                    "ref":"main",
                    "inputs":{
                        "Tag":"${{ steps.new-tag.outputs.tag }}",
                        "ReleaseBody":"${{ inputs.ReleaseInfoFile }}",
                        "ReleaseName":"${{ github.event.inputs.ReleaseName }}"
                    }
                }'
            done

        
