name: Trigger Target Workflow

on:
  workflow_dispatch:
    inputs:
      target_workflow:
        description: 'The name of the workflow to trigger'
        required: true
        default: 'create-pull-request'
      branch_name:
        description: 'Merge branch name'
        type: string
        required: true
        default: 'Sprint-1-merge'
      pr_type:
        description: 'Type of pull request'
        type: choice
        required: true
        options:
          - 'Sprint-Close'
          - 'Patch'
      pr_description:
        description: 'Description of the pull request'
        type: string
        required: false
        default: 'Update report'
      source_branch:
        description: 'Branch to create pull request from'
        type: string
        required: true
        default: 'develop'
      target_branch:
        description: 'Branch to create pull request to'
        type: string
        required: true
        default: 'main'

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Target Workflow - Powershell
        run: |          
          curl -L -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.REPO_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/RobertPuffeEldermark/PowerShell/actions/workflows/${{ github.event.inputs.target_workflow }}/dispatches \
          -d '{"ref":"main","inputs":{"branch_name":"${{ github.event.inputs.branch_name }}","pr_type":"${{ github.event.inputs.pr_type }}","pr_description":"${{ github.event.inputs.pr_description }}","source_branch":"${{ github.event.inputs.source_branch }}","target_branch":"${{ github.event.inputs.target_branch }}"}}'
