name: Trigger Create Release

on: 
  workflow_dispatch:
    inputs:
        target_workflow:
            description: 'The filename of the workflow to trigger'
            required: true
            default: 'createrelase_local.yml'
        ReleaseName:
            description: 'Name of release. ex. Sprint 6 Close'
            type: string
            required: true
        DeploymentInstructions:
            description: 'Deployment Instructions'
            required: false
            type: string
            default: 'Include tickets if possible [https://eldermark.atlassian.net/browse/EMAR-582](https://eldermark.atlassian.net/browse/EMAR-582)'
        IncludePipelineMicroservices:
            description: 'Include default list of clinical microservices'
            type: string
            default: '          ### Microservices deployed:\n            \n          **Clinical Pipeline**\n          \n          - api-gateway\n          - assessment\n          - audit\n          - billing\n          - crm\n          - emar-sync\n          - eureka\n          - event\n          - housing\n          - mirth-service\n          - notification\n          - org\n          - resident\n          - rm\n          - web\n          \n          **EMAR Pipeline**\n          \n          - emar-cluster\n          - emar-data-api\n'
        ReleaseInfoFile:
            description: 'Release Info File'
            type: string
            required: true
            default: 'releases/ReleaseInfo.md'
jobs:
    # ToDo: use github api to get tags from each repository and calculate new tag. 
    # ToDo: Add concurrency
    trigger-create-release:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Code
          uses: actions/checkout@v4
        
        # get body markdown file from this repository in the path releases/ReleaseInfo.md
        - name: get body markdown file
          id: get-body
          run: |
            echo "RELEASE_BODY=$(cat ${{ github.event.inputs.ReleaseInfoFile }})" >> $GITHUB_OUTPUT

        # Trigger Repository 1
        - name: Trigger Target Workflow - Powershell
          run: |          
            curl -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPO_TOKEN_RP }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/RobertPuffeEldermark/PowerShell/actions/workflows/${{ github.event.inputs.target_workflow }}/dispatches \
            -d '{"ref":"main","inputs":{"ReleaseBody":"${{ steps.get-body.outputs }}","ReleaseName":"${{ github.event.inputs.ReleaseName }}","IncludePipelineMicroservices":"${{ github.event.inputs.IncludePipelineMicroservices }}"}}'
        # Repeat the above step for each repository

    # ToDo: validate tag was created in all repositories
