name: Trigger Create Release

on: 
  workflow_dispatch:
    inputs:
        target_workflow:
            description: 'The name of the workflow to trigger'
            required: true
            default: 'create-release'
        DeploymentInstructions:
            description: 'Deployment Instructions'
            required: false
            default: 'Include EMAR-582 script that must be run against each community database. [https://eldermark.atlassian.net/browse/EMAR-582](https://eldermark.atlassian.net/browse/EMAR-582)'

jobs:
    # ToDo: use github api to get tags from each repository and calculate new tag. 
    # ToDo: Add concurrency
    trigger-create-release:
        runs-on: ubuntu-latest
        steps:
        # Trigger Repository 1
        - name: Trigger Target Workflow - Powershell
          run: |          
            curl -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPO_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/RobertPuffeEldermark/PowerShell/actions/workflows/${{ github.event.inputs.target_workflow }}/dispatches \
            -d '{"ref":"main","inputs":{"DeploymentInstructions":"${{ github.event.inputs.DeploymentInstructions }}"}}'
        # Repeat the above step for each repository
