name: Trigger Create Release

on: 
  workflow_dispatch:
    inputs:
        target_workflow:
            description: 'The filename of the workflow to trigger'
            required: true
            default: 'createrelase_local.yml'
        ReleaseInfoFile:
            description: 'Release Info File'
            type: string
            required: true
            default: 'releases/ReleaseInfo.md'
        ReleaseName:
            description: 'Name of release. ex. Sprint 6 Close'
            type: string
            default: 'Eldermark Next'
            required: true
env:
    REPOSITORIES: "RobertPuffeEldermark/PowerShell RobertPuffeEldermark/test-auto-pr-2"
jobs:
    # ToDo: Add concurrency
    trigger-create-release:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: check if release info file exists
          run: |
            if [ ! -f "${{ inputs.ReleaseInfoFile }}" ]; then
                echo "Release Info File not found"
                exit 1
            fi

        - name: Get the date
          id: get-date
          run: echo "date=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT

        - name: fetch tags on repos
          id: fetch-tags
          run: |
            GREATEST_TAG=0000.00.00.0000
            IFS=' ' read -r -a REPO_ARRAY <<< "${{ env.REPOSITORIES }}"
            for REPO in "${REPO_ARRAY[@]}" ; do
                TAG=$(curl -L -X GET \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.REPO_TOKEN }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/$REPO/git/refs/tags \
                | jq -r '.[] | select(.ref | contains("${{ steps.get-date.outputs.date }}")) | .ref' | cut -d '/' -f 3 | sort -V | tail -n 1)
                echo "Tag for $REPO is $TAG"
                # Check if tag is greater than GREATEST_TAG
                if [[ $TAG > $GREATEST_TAG ]]; then
                    GREATEST_TAG=$TAG
                    echo "GREATEST_TAG=$GREATEST_TAG" >> $GITHUB_OUTPUT
                    echo "greater tag found $TAG"
                fi
            done
        
        - name: Calculate new tag
          id: new-tag
          run: |
            OLD_TAG=${{ steps.fetch-tags.outputs.GREATEST_TAG}}
            if [[ -z "$OLD_TAG" ]]; then
            echo "tag=${{ steps.get-date.outputs.date }}.0001" >> $GITHUB_OUTPUT
            else
            NUMBER=$(echo $OLD_TAG | awk -F. '{print $NF}')
            NEW_NUMBER=$(printf "%04d" $((10#$NUMBER + 1)))
            echo "tag=${{ steps.get-date.outputs.date }}.$NEW_NUMBER" >> $GITHUB_OUTPUT
            fi

        # Trigger Repositories
        - name: Trigger Target Workflow - Powershell
          run: |    
            IFS=' ' read -r -a REPO_ARRAY <<< "${{ env.REPOSITORIES }}"
            for REPO in "${REPO_ARRAY[@]}" ; do
                echo "Triggering workflow for $REPO"   
                curl -L -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.REPO_TOKEN_RP }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/$REPO/actions/workflows/${{ github.event.inputs.target_workflow }}/dispatches \
                -d '{
                    "ref":"main",
                    "inputs":{
                        "Tag":"${{ steps.new-tag.outputs.tag }}",
                        "ReleaseBody":"${{ inputs.ReleaseInfoFile }}",
                        "ReleaseName":"${{ github.event.inputs.ReleaseName }} ${{ steps.new-tag.outputs.tag }}",
                    }
                }'
            done

        
