name: trigger-pull-request

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Merge branch name'
        type: string
        required: true
        default: 'Sprint-1'
      pr_type:
        description: 'Type of pull request'
        type: choice
        required: true
        options:
          - 'Sprint-Close'
          - 'Patch'
          - 'Hotfix'
      pr_title_append:
        description: 'Title - Append to title of the pull request'
        type: string
        required: false
      pr_body:
        description: 'Body of the pull request - add additional details here'
        type: string
        required: false
      source_branch:
        description: 'Branch to create pull request from - default is develop'
        type: string
        required: true
        default: 'develop'
      target_branch:
        description: 'Branch to create pull request to - default is main'
        type: string
        required: true
        default: 'main'

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      # Trigger Repository 1
      - name: Append Branch Name
        id: append-branch-name
        run: |
          RUN_ID_SUFFIX=${{ github.run_id }}
          RUN_ID_SUFFIX=${RUN_ID_SUFFIX:0:5}
          echo "branch_name=${{ github.event.inputs.branch_name }}-${{ github.event.inputs.pr_type }}-$RUN_ID_SUFFIX" >> $GITHUB_OUTPUT

      - name: Trigger Target Workflow - Powershell
        run: |          
          REPO=("RobertPuffeEldermark/PowerShell" "RobertPuffeEldermark/test-auto-pr-2")
          echo "branch name is ${{ steps.append-branch-name.outputs.branch_name }}"
          for REPO in "${REPO[@]}" ; do
            echo "Triggering workflow for $REPO"
            curl -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPO_TOKEN_RP }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$REPO/actions/workflows/create-pull-request.yml/dispatches \
            -d '{
              "ref":"main",
              "inputs":{
                "branch_name":"${{ steps.append-branch-name.outputs.branch_name }}",
                "pr_type":"${{ github.event.inputs.pr_type }}",
                "pr_title":"${{github.event.inputs.branch_name}}-${{ github.event.inputs.pr_type }} ${{ github.event.inputs.pr_title_append }}",
                "pr_body":"${{ github.event.inputs.pr_body }} This is an automated pull request.",
                "source_branch":"${{ github.event.inputs.source_branch }}",
                "target_branch":"${{ github.event.inputs.target_branch }}"
              }
            }'
          done
