name: Trigger Create PR

on:
  workflow_dispatch:
    inputs:
      target_workflow:
        description: 'The filename of the workflow to trigger'
        required: true
        default: 'autopullrequest_local.yml'
      branch_name:
        description: 'Merge branch name'
        type: string
        required: true
        default: 'Sprint-1-merge'
      pr_type:
        description: 'Type of pull request'
        type: choice
        required: true
        options:
          - 'Sprint-Close'
          - 'Patch'
      pr_title:
        description: 'Title of the pull request'
        type: string
        required: true
        default: 'Update report'
      pr_body:
        description: 'Body of the pull reques'
        type: string
        required: true
        default: 'This is an automated pull request'
      source_branch:
        description: 'Branch to create pull request from'
        type: string
        required: true
        default: 'develop'
      target_branch:
        description: 'Branch to create pull request to'
        type: string
        required: true
        default: 'main'

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      # Trigger Repository 1
      - name: Append Branch Name
        id: append-branch-name
        run: |
          RUN_ID_SUFFIX=${{ github.run_id }}
          RUN_ID_SUFFIX=${RUN_ID_SUFFIX:0:5}
          echo "branch_name=${{ github.event.inputs.branch_name }}-$RUN_ID_SUFFIX" >> $GITHUB_OUTPUT

      - name: Trigger Target Workflow - Powershell
        run: |          
          REPO=("RobertPuffeEldermark/PowerShell" "RobertPuffeEldermark/test-auto-pr-2")
          echo "branch name is ${{ steps.append-branch-name.outputs.branch_name }}"
          for REPO in "${REPO[@]}" ; do
            echo "Triggering workflow for $REPO"
            curl -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPO_TOKEN_RP }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$REPO/actions/workflows/${{ github.event.inputs.target_workflow }}/dispatches \
            -d '{
              "ref":"main",
              "inputs":{
                "branch_name":"${{ steps.append-branch-name.outputs.branch_name }}",
                "pr_type":"${{ github.event.inputs.pr_type }}",
                "pr_title":"${{ github.event.inputs.pr_title }}",
                "pr_body":"${{ github.event.inputs.pr_body }}",
                "source_branch":"${{ github.event.inputs.source_branch }}",
                "target_branch":"${{ github.event.inputs.target_branch }}"
              }
            }'
          done
